---

# Build the requested container
- name: Create container {{ docker_name }}
  command: "{{ ansible_docker_utils_paths.docker }} build -t {{ docker_name }} -f {{ docker_dockerfile }} {{ docker_build_args }} {{ docker_base_dir }}"
  register: result

- debug: var=result.stdout_lines

- name: Return only the build result
  set_fact:
    docker_result: "{{ result.stdout_lines }}"

- debug: var=docker_result