---

# Create the requested volume

- name: Create volume {{ docker_name }} if it doesn't exist
  command: "{{ ansible_docker_utils_paths_docker }} volume create --name {{ docker_name }}"
  register: result
