---

# Check if postgres is up
- name: Check if {{ docker_name }} is up
  command: "{{ ansible_docker_utils_paths.docker }} exec {{ docker_name }} {{ ansible_docker_utils_paths.pg_isready }}"
  until: "'- accepting connections' in result.stdout"
  register: result
  retries: "{{ docker_retries }}"
  delay: "{{ docker_delay }}"

- name: Return status (hopefully "True")
  set_fact:
    docker_result: True
  when: "'- accepting connections' in result.stdout"
