---

# Check if redis is up
- name: Check if {{ docker_name }} is up
  command: "{{ ansible_docker_utils_paths.docker }} exec {{ docker_name }} {{ ansible_docker_utils_paths.redis_cli }} ping"
  register: result
  when: docker_auth_required
  until: "'NOAUTH Authentication required' in result.stdout"
  retries: "{{ dockers_retries }}"
  delay: "{{ docker_delay }}"

# Check if redis is up
- name: Check if {{ docker_name }} is up
  command: "{{ ansible_docker_utils_paths.docker }} exec {{ docker_name }} {{ ansible_docker_utils_paths.redis_cli }} ping"
  register: result
  when: not docker_auth_required
  until: "'PONG' in result.stdout"
  retries: "{{ docker_retries }}"
  delay: "{{ docker_delay }}"



- name: Return status (hopefully "True")
  set_fact:
    docker_result: True
  when: "'NOAUTH Authentication required' in result.stdout"
