---

# Check if rabbitmq-server is up
- name: Check if rabbitmq-server on {{ docker_name }} is up
  command: "{{ ansible_docker_utils_paths_docker }} exec {{ docker_name }} ps ax"
  register: result
  until: "'rabbitmq-server' in result.stdout"
  retries: "{{ docker_retries }}"
  delay: "{{ docker_delay }}"


# Check if the Management Console is up
- name: Check if the Management Console on {{ docker_name }} is up
  command: "{{ ansible_docker_utils_paths_docker }} exec {{ docker_name }} {{ ansible_docker_utils_paths_rabbitmqctl }} status"
  register: result
  until: "'RabbitMQ Management Console' in result.stdout"
  retries: "{{ docker_retries }}"
  delay: "{{ docker_delay }}"


# Check if the permissions have been set
- name: Check if the permissions on vhost {{ docker_vhost }} on {{ docker_name }} is up
  command: "{{ ansible_docker_utils_paths_docker }} exec {{ docker_name }} {{ ansible_docker_utils_paths_rabbitmqctl }} list_permissions -p {{ docker_vhost }}"
  register: result
  until: "'guest' in result.stdout"
  retries: "{{ docker_retries }}"
  delay: "{{ docker_delay }}"

- name: Return status
  set_fact:
    docker_result: True
  when: "'guest' in result.stdout"
