---

# Get a list of dangling containers
- name: Get the list dangling containers
  command: "{{ ansible_docker_utils_paths_docker }} images -f 'dangling=true' -q"
  register: result

- name: Return only the dangling containers
  set_fact:
    docker_result: "{{ result.stdout_lines }}"

