---

# Get a list of dangling containers
- name: Get the list dangling containers
  command: docker images -f "dangling=true" -q
  register: result

- debug: var=result

- name: Return only the dangling containers
  set_fact:
    docker_result: "{{ result.stdout_lines }}"

- debug: var=docker_result

