---

# Remove the image (force it!)

- name: Forcibly remove the volume {{ docker_name }}
  command: "{{ ansible_docker_utils_paths_docker }} volume rm {{ docker_name }}"
  ignore_errors: true
  register: docker_result

