---

# Remove the image (force it!)

- name: Forcibly remove the image {{ docker_name }}
  command: "{{ ansible_docker_utils_paths.docker }} rmi -f {{ docker_name }}"
  ignore_errors: true
  register: docker_result

