---

# Remove the image (force it!)

- name: Forcibly remove the image {{ docker_name }}
  command: "{{ paths.docker }} rmi -f {{ docker_name }}"
  ignore_errors: true
  register: docker_result

- debug: var=docker_result.stdout

