---

# Set the name to the image if it is not defined
- name: Set container name if it is not defined
  set_fact:
    docker_container_name: "{{ docker_name }}"
  when: docker_container_name is not defined

# Run the requested container
- name: Run container {{ docker_container_name }}
  command: "{{ ansible_docker_utils_paths_docker }} run {{ docker_extra_args }} {{ docker_volume_args }} --privileged=True
             --name={{ docker_container_name }} --hostname={{ docker_container_name }}.{{ docker_domain_name }} {{ docker_name }} {{ docker_command }}"
  when: docker_command is defined
  register: result_with_command

# Run the requested container
- name: Run container {{ docker_container_name }}
  command: "{{ ansible_docker_utils_paths_docker }} run {{ docker_extra_args }} {{ docker_volume_args }} --privileged=True
             --name={{ docker_container_name }} --hostname={{ docker_container_name }}.{{ docker_domain_name }} {{ docker_name }}"
  when: docker_command is not defined
  register: result_without_command

- name: Return only the build result
  set_fact:
    docker_result: "{{ result_with_command.stdout_lines }}"
  when: docker_command is defined

- name: Return only the build result
  set_fact:
    docker_result: "{{ result_without_command.stdout_lines }}"
  when: docker_command is not defined
